config/routes.rb
Rails.application.routes.draw do
  resources :issues
   resources :issues do
    resources :comments
  end
  
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  root 'application#hello'
end

IssueTracker::Application.routes.draw do
  resources :issues
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/home/show')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/watch' => "issues#watch", as: :watch
  put '/issues/:id/status' => "issues#update_status", as: :update_status
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id, optional: true
  has_many :votes, dependent: :destroy
  has_many :watchers, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, :tipus, :priority, :status, presence: true

 
  def self.tipus
  ["Bug", "Enhancement", "Proposal", "Task"]
  end
  def self.priority
  ["Trivial", "Minor", "Major", "Critical", "Blocker"]
  end
  def self.status
  ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  #acts_as_token_authentication_handler_for User
  before_action :authenticate
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  # GET /issues
  # GET /issues.json
  #def index
  #  redirect_to "/home/show" if not current_user
  #  @issues = Issue.all.order(sort_column + ' ' + sort_direction)
  
  def index
    respond_to do |format|  
      @issues = Issue.all.order(sort_column + ' ' + sort_direction)
      @issues = @issues.where(tipus: params[:tipus])  if params.has_key?(:tipus)
      @issues = @issues.where(priority: params[:priority]) if params.has_key?(:priority)
    
      if params.has_key?(:watcher)
          if User.exists?(id: params[:watcher])
            @issues = Issue.joins(:watchers).where(watchers:{user_id: params[:watcher]})
          end
      end
          
      if params.has_key?(:assignee)
        if User.exists?(id: params[:assignee])
          @issues = @issues.where(assignee_id: params[:assignee])
        end
      end
      
      if params.has_key?(:status)
        if params[:status] == "New&Open"
          @issues = @issues.where(status: ["Open","New"])
        else
        @issues = @issues.where(status: params[:status])
        end
      end
      format.html
      format.json {render json: @issues, status: :ok}
    end
    
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @issue, status: :ok, serializer: IssueSerializer}
    end
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.created_at = Time.now
    @issue.updated_at = Time.now
    @issue.user_id = @current_user.id
    

    respond_to do |format|
      if @issue.save
        @watcher = Watcher.new
          @watcher.user_id = @current_user.id
          @watcher.issue_id = @issue.id
          @watcher.save
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render json: @issue, status: :created, serializer: IssueSerializer }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    
    @issue = Issue.find(params[:id])
    if @issue.assignee_id != params[:assignee_id]
        @comment = Comment.new
        @comment.issue_id = @issue.id
        @comment.user_id = @current_user.id
        @comment.body =  " assigned issue to " + User.find(params[:assignee_id]).name
        @comment.save 
    end
    if @issue.status != params[:status]
        @comment = Comment.new
        @comment.issue_id = @issue.id
        @comment.user_id = current_user.id
        @comment.body =  " assigned issue to " + issue_params.status
        @comment.save 
    end
    respond_to do |format|
      if @issue.update(issue_params)
        
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue, serializer: ShowIssueSerializer }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_status
    respond_to do |format|
      @issue_to_update = Issue.find(params[:id])
      @issue_to_update.update_attribute("status", params[:status])
       @comment = Comment.new
       @comment.issue_id = @issue_to_update.id
        @comment.user_id = @current_user.id
        @comment.body =  "changed status to " + @issue_to_update.status 
        @comment.save 
      format.html { redirect_to @issue_to_update }
      format.json { render json: @issue_to_update, status: :ok }
    end
  end


  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { render json: {message: 'Issue deleted successfully'}, status: :ok }
    end
  end
  
    # POST /issues/{issue_id}/watch
  
  def watch
    respond_to do |format|
      @issue_to_watch = Issue.find(params[:id])
      if !Watcher.exists?(:issue_id => @issue_to_watch.id, :user_id => @current_user.id)
        @watcher = Watcher.new
        @watcher.user_id = @current_user.id
        @watcher.issue_id = @issue_to_watch.id
        @watcher.save
      else
        @watcher = Watcher.where(issue_id: params[:id], user_id: @current_user.id).take
        @watcher.destroy
      end
      if params[:view] == "index"
        format.html { redirect_to issues_url}
      else
        format.html { redirect_to @issue_to_watch}
      end
      format.json { render json: @issue_to_watch, status: :ok }
    end
  end
  
  # POST /issues/{issue_id}/vote
  
  def vote
    respond_to do |format|
      @issue_to_vote = Issue.find(params[:id])
      if !Vote.exists?(:issue_id => @issue_to_vote.id, :user_id => @current_user.id)
        @vote = Vote.new
        @vote.user_id = @current_user.id
        @vote.issue_id = @issue_to_vote.id
        @vote.save
      else
        @vote = Vote.where(issue_id: params[:id], user_id: @current_user.id).take
        @vote.destroy
      end
      
      format.html { redirect_to @issue_to_vote }
      format.json { render json: @issue_to_vote, status: :ok }
     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :tipus, :priority, :status, :user_id, :created_at, :updated_at, :assignee_id, :watching, :votes)
    end
    
    def sort_column
      Issue.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <div  class = "formLabel"> 
    <%= form.label :title %>
    </div>
    <div class = "formInput"> 
    <%= form.text_field :title, id: :issue_title %>
    </div>
  </div>

  <div class="input-group">
    <div class = "formLabel"> 
    <%= form.label :description %>
    </div>
    <div class = "formInput"> 
    <%= form.text_field :description, id: :issue_description %>
    </div>
  </div>
  
  <div class="input-group">
    <div class = "formLabel"> 
    <%= form.label :assignee_id %>
    </div>
    <div class = "formInput"> 
    <%= form.collection_select :assignee_id, User.all, :id, :name, {:include_blank => 'No assigned user yet'}  %>
    </div>
  </div>

  <div class="input-group">
    <div class = "formLabel"> 
    <%= form.label :tipus %>
    </div>
    <div class = "formInput"> 
    <%= form.select :tipus, options_for_select(Issue.tipus, issue[:tipus]) %>
    </div>
  </div>

  <div class="input-group">
    <div class = "formLabel"> 
    <%= form.label :priority %>
    </div>
    <div class = "formInput"> 
    <%= form.select :priority, options_for_select(Issue.priority, issue[:priority])%>
    </div>
  </div>

  <div class="input-group">
    <div class = "formLabel"> 
    <%= form.label :status %>
    </div>
    <div class = "formInput"> 
    <%= form.select :status, options_for_select(Issue.status) %>
    </div>
  </div>

  <br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<div style="margin-top:60px;"> 

<titNew> <h1>Edit Issue</h1> </titNew>
</div>

<div style ="margin-left:40%; margin-top:70px"> 
<%= render 'form', issue: @issue %>
</div>
<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<tit> 
<div class="header">
  <div class="section-title">
    
  </div>
</div>
</tit>


<div style= "margin-top:70px; margin-left:70px; font-size:16px"> 
  <div>
    <strong style="font-size:20px;margin-top:40px" >Issues</strong>
    <p style="margin-top:40px"> 
      Filter by:
          <a href="/issues">All</a>
      
          <a><%= link_to "Open", issues_url(status: "New&Open")%></a>
          <a><%= link_to "My issues", issues_url(assignee: current_user.id)%></a>
          <a><%= link_to "Watching", issues_url(watcher: current_user.id)%></a>
          </p>
    
</div>

<div style= " margin-top:40px" > 
<p> <strong >Issues (<%= @issues.size %>)  </strong>
<% if current_user %>
    <span style="margin-left:1200px"> 
      <%= link_to new_issue_path, class: 'create-button' do %>
        <span class="glyphicon glyphicon-plus"></span>
        <span class="createi-button">Create issue</span>
      <% end %>
      </span>
    
    <% end %></p>
</div>
</div>



<div class="page-actions">
   
</div>

<div style= "margin-top:70px; margin-left:70px; font-size:16px">
    <% if request.query_parameters[:tipus] %>
      <strong>Type:</status> "<%= request.query_parameters[:tipus] %>"
    <% end %>
    <% if request.query_parameters[:priority] %>
        <strong>Priority:</strong> "<%= request.query_parameters[:priority] %>"
    <% end %>
    <% if request.query_parameters[:status] %>
        <strong>Status:</strong> "<%= request.query_parameters[:status] %>"
    <% end %>
    <% if request.query_parameters[:assignee] %>
        <strong>Assignee:</strong> "<%= User.find(request.query_parameters[:assignee]).name %>"
    <% end %>
</div>

<b> 
<table class="issue-list">
  <thead>
    <tr>
      <a> 
      <t1> 
      <th scope="col"><%= sortable "title" %></th>
      <th scope="col"><%= sortable "tipus", "Type" %></th>
      <th scope="col"><%= sortable "priority" %></th>
      <th scope="col"><%= sortable "status" %></th>
      <th scope="col"><%= sortable "votes" %></th>
      <th scope="col"><%= sortable "assignee_id", "Assignee" %></th>
      <th scope="col"><%= sortable "created_at", "Created" %></th>
      <th scope="col"><%= sortable "updated_at", "Updated" %> </th>
      <th scope="col"></th>
      <th colspan="3"></th>
      </t1>
      </a>
    </tr>
  </thead>
  </b>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to issue.title , issue %></td>
        <td><%= link_to issue.tipus , issues_url(tipus: issue.tipus)%></td>
        <td><%= link_to issue.priority , issues_url(priority: issue.priority) %></td>
        <td><%= link_to issue.status , issues_url(status: issue.status) %></td>
        <td><%= link_to issue.votes.size, issues_url(votes: issue.votes.size) %></td>
        <% if !issue.assignee.nil? %>
            <td><%= link_to issue.assignee.name, issues_url(assignee: issue.assignee.id)%></td>
            <% else %>
            <td></td>
        <% end %>
        <td><%= time_ago_in_words(issue.created_at) + " ago" %></td>
        <td><%=  time_ago_in_words(issue.updated_at) + " ago"  %></td>
      
        <td><% if !Watcher.exists?(:issue_id => issue.id, :user_id => current_user.id) %>
              <%= link_to 'Watch', watch_url(id: issue.id, view: "index"), method: :post %>
            <%else %>
              <%= link_to 'Stop watching', watch_url(id: issue.id, view: "index"), method: :post %>
          <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/issues/new.html.erb
<div style="margin-top:60px;"> 
<titNew> <h1>Issue</h1>
<h2>Create issue</h2></titNew>
</div>


<div style ="margin-left:40%; margin-top:70px"> 
<%= render 'form', issue: @issue %>
</div>
<div> 
<%= link_to 'Back', issues_path %>
</div>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>


<issShow>
  
  <div style= "margin-top: 65px">
    <div align="center" class="float-left">
      <div class="issue-header">
      
        
        <div> <issTitle> <%= @issue.title %></issTitle></div>
        
        <issName> 
        <span style="font-size:13px" class="issue-id">
          Issue #<%= @issue.id %>
        </span>
        <span style="font-style:italic" class="issue-status">
          <%= @issue.status %>
        </span>
        </issName>
      </div>

<div style= "border-radius: 5px;padding:8px">

      <div >
        <issName> 
         <img src="/assets/96.png" style="margin:auto;margin-right:6px;width:40px; height:40px; display: inline-block; border-radius:90px">
        <div style = " display: inline-block;"><span style = "color:blue; margin-left:4px">  <%=@issue.user.name %> </span>   created an issue  <time class="created_at"><%= @issue.created_at.strftime('%Y-%m-%d')%></time> </div>
          </issName>
          
      </div>

      <div >
        <issName> 
        <% if @issue.description %>
         <p style = "margin-left:15px; font-style:italic"><%= @issue.description %></p>
        <% else %>
          <p>No description provided.</p>
        <% end %>
        </issName>
      </div>
      </div>
      <hr>
       <div style="text-align: left;" class="issue-comments-container">
        
        <p style= "font-weight:bold">Comments (<%= @issue.comments.size %>)</p>
        
        <% @issue.comments.each do |comment| %>
          <div style= "background-color:white ;border-radius: 20px;padding:8px" >
   
             
   
            <div>
             <img src="/assets/96.png" style="margin:auto;margin-right:6px;width:40px; height:40px; display: inline-block; border-radius:90px">
             <div style ="display: inline-block;font-weight:bold;color:blue;">  <%= comment.user.name %> </div>
              
            </div>
        
            <div style = "margin-left:100px; margin-top:20px; font-style:italic">
            
            <div> <%= comment.body%></div> 
            </div>
            
          <p style= "font-size:11px">  <%= time_ago_in_words(comment.created_at) + " ago" %>
              <% if comment.user.id == current_user.id %>
          |   <%= link_to 'Delete', [comment.issue, comment],
                       method: :delete , class: "esborrar" %>
              <%= link_to 'Edit', [comment.issue, comment],
                       method: :put , class: "editar" %>
              <% end %>
          </p> 
          </div>
          </br>
        <% end %>
        
        <%= form_with(model: [@issue, @issue.comments.build], local: true) do |form| %>
          <div style = "text-align: center;">
            <%= form.text_area :body, placeholder:'What do you want to say?' %>
          </div>
          <div style = "text-align: center;" class="actions">
            <%= form.submit %>
          </div>
        <% end %>
        <%= form_with(model: [@issue, @issue.comments.build], local: true) do |form| %>
          <div style = "text-align: center;">
            <%= form.text_area :body, placeholder:'Select a File?' %>
          </div>
          <div style = "text-align: center;" class="actions">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
</div>
      
    </div>
    


<div style="background-color: white ;margin-left: 250px;border-style: solid;border-color: lightgrey;border-radius: 5px;border-width: 1px;" align="center" class="float-left">
  
  <tools>
  <p>
    
   <strong> Assignee: </strong>
   <% if !@issue.assignee.nil? %>
              <a href="/issues?assignee=<%= @issue.assignee.id%>">
                <span title="assignee"><%= @issue.assignee.name%></span>
              </a>
              <% else %>
              No one assigned
    <% end %>
    
  </p>
  
  <p>
    
    <strong>Type: </strong>
     <%= link_to @issue.tipus, issues_url(tipus: @issue.tipus) %>
     
  </p>
  
  <p>
    <strong>Priority: </strong>
     <%= link_to @issue.priority, issues_url(priority: @issue.priority) %>
  </p>
  
  <p>
    <strong>Status: </strong>
     <%= link_to @issue.status, issues_url(status: @issue.status) %>
  </p>
  
  <p>
    <strong>Votes: </strong>
  
      <%= @issue.votes.size%>
        <% if !Vote.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
          <%= link_to 'Vote for this issue', vote_url(id: @issue.id), method: :post%>
        <% else %>
          <%= link_to 'Remove vote', vote_url(id: @issue.id), method: :post%>
        <% end %>
      </span>
  </p>
  
  <p>
    <strong>Watchers: </strong>
      <%= @issue.watchers.size %>
        <% if !Watcher.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
          <%= link_to 'Watch this issue', watch_url(id: @issue.id), method: :post%>
        <% else %>
          <%= link_to 'Stop Watching', watch_url(id: @issue.id), method: :post%>
        <% end %>
      </span>
  </p>
  
  <p>
  


 
<div class="issue-toolbar">
  <% if current_user %>
        <span>
              <% if @issue.status == "Open" || @issue.status == "New" %>
               <div class="buttDiv"> <button class="butt"> <%= link_to 'Resolve', update_status_url(id: @issue.id, status: "Resolved"), method: :put %> </button> </div> 
              <% else %>
               <div class="buttDiv"> <button class="butt">  <%= link_to 'Open', update_status_url(id: @issue.id, status: "Open"), method: :put, class:'open'%> </button> </div>
              <% end %>
            </span>
              <div class="dropdown">
                <button class="dropbtn">Workflow</button>
                <div class="dropdown-content">
                  <% Issue.status.each do |status| %>
                  <% if status != @issue.status %>
                    <%= content_tag(:span, link_to(status, update_status_url(id: @issue.id, status: status), method: :put)) %>
                  <% end %>
                <% end %>
                </div>
              </div>
              
           </tools>
   
             <div style = "margin-top: 25px; padding:6px; margin-left: 10px"> 
                <a href="/issues/<%= @issue.id %>/edit" class="aui-button">Edit</a>
                <%= link_to 'Delete', @issue,  method: :delete, class: 'aui-button', data: { confirm: 'Are you sure you want to delete this issue?' } %>
                <%= link_to 'Back', issues_path %>
                <% if current_user %>
      <%= link_to new_issue_path, class: 'create-button' do %>
        <span>Create issue</span>
      <% end %>
      
    <% end %>
            </div>

  <% end %>
</div>
</div>


</issShow>


</div>